name: Makefile CI

on:
  push:
    branches: 
      - "master" # Changed from $default-branch to "master"
  pull_request:
    branches: 
      - "master" # Changed from $default-branch to "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Run Unit Test
      run: make unit_tests