name: Makefile CI

on:
  push:
    branches: 
      - "master" # Changed from $default-branch to "master"
  pull_request:
    branches: 
      - "master" # Changed from $default-branch to "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5'
    - name: Install dependencies
      run: python -m pip install poetry
    - name: Install project dependencies
      run: python -m pip install "scikit-learn>=1.7.2,<2.0.0" matplotlib pandas fastapi fastapi-cli fastapi-cloud-cli streamlit streamlit-drawable-canvas pytest

    - name: Run Unit Test
      run: make unit_tests