name: Makefile CI

on:
  push:
    branches: 
      - "master" # Changed from $default-branch to "master"
  pull_request:
    branches: 
      - "master" # Changed from $default-branch to "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
    uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: python -m pip install poetry
    - name: Install project dependencies
      run: poetry install

    - name: Run Unit Test
      run: make unit_tests